### ISSUE TITLE
Sending messages to non existed sockets

### ISSUE THREAD

**Issue by ManuGowda** [Unitech/pm2-axon#11]
We are using `pm2-axon` in our project for IPC communication, while handling the socket cleanup at application layer are receiving the following error as the socket does not exists while sending message.

```
Message: Cannot read property 'writable' of undefined
 Trace: TypeError: Cannot read property 'writable' of undefined
    at PubSocket.send (sdk/node_modules/pm2-axon/lib/sockets/pub.js:51:14)
    at Bus.publish (sdk/framework/dist-node/controller/bus.js:115:29)
    at PullSocket.<anonymous> (sdk/framework/dist-node/controller/bus.js:51:18)
    at PullSocket.emit (events.js:315:20)
    at Parser.<anonymous> (sdk/node_modules/pm2-axon/lib/sockets/sock.js:225:15)
    at Parser.emit (events.js:315:20)
    at Parser._write (sdk/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Parser.Writable.write (_stream_writable.js:318:11)
```

Possible solution would be to use `this.socks.length` to iterate and send message to each socket
```
PubSocket.prototype.send = function (msg) {
  var buf = this.pack(arguments);

  for (var i = 0; i < this.socks.length; i++) {
    const sock = this.socks[i];
    if (sock && sock.writable) sock.write(buf);
  }

  return this;
};
```

**Comment by Unitech** [comment]
fixed via https://github.com/Unitech/pm2-axon/pull/9
